version: '3.8'
services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=facebluk
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5433:5432'
    volumes:
      - ./docker-data/database:/var/lib/postgresql/data

  document-db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./docker-data/document-db/data:/data/db
  
  textsearch-db:
    image: elasticsearch:8.7.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=https://app.elasticvue.com
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - ./docker-data/textsearch-db:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  message-broker:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./docker-data/message-broker:/var/lib/rabbitmq
