version: '3.8'
services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=facebluk
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5433:5432'
    volumes:
      - ./docker-data/database:/var/lib/postgresql/data

  message-broker:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./docker-data/message-broker:/var/lib/rabbitmq
