export * as AcceptFriendRequest from './accept-friend-request-consumer'
export * as CancelFriendRequest from './cancel-friend-request-consumer'
export * as RejectFriendRequest from './reject-friend-request-consumer'
export * as SendFriendRequest from './send-friend-request-consumer'
export * as FriendRequestSent from './friend-request-sent-consumer'
export * as FriendRequestRejected from './friend-request-rejected-consumer'
export * as FriendRequestCancelled from './friend-request-cancelled-consumer'
export * as FriendRequestAccepted from './friend-request-accepted-consumer'